<?php

$options = [
    'adgeziya' => 'Адгезия',
    'amount_am' => 'Кол-во на а/м',
    'class-pojar' => 'Класс пожарной опасности материала',
    'classprotivosk' => 'Класс противоскольжения',
    'collection' => 'Коллекция',
    'cvet' => 'Цвет',
    'cvet-proizvoditelya' => 'Цвет производителя',
    'ehkspluatacionnaya-nagruzka-cherez-ch' => 'Эксплуатационная нагрузка через, ч',
    'factsoprotteploper' => 'Фактическое сопротивление теплопередачи, Ro (С*м2/Вт)',
    'factura' => 'Фактура',
    'faska' => 'Фаска',
    'forma' => 'Форма',
    'format' => 'Формат',
    'frostres_grade' => 'Марка морозостойкости',
    'garantiya' => 'Гарантия, лет',
    'gruppa-istiraem' => 'Группа истираемости',
    'gruppa_goryuchesti' => 'Группа горючести',
    'indeks-izolyacii-vozdushnogo-shuma' => 'Индекс изоляции воздушного шума',
    'item_length' => 'Длина, мм',
    'item_thickness' => 'Толщина, мм',
    'item_width' => 'Ширина, мм',
    'iznosostojkost' => 'Износостойкость',
    'kislotostojkost' => 'Кислотостойкость, %',
    'klassbetona' => 'Класс бетона по прочности на сжатие, В',
    'klassplotnosti' => 'Класс плотности',
    'kolichestvo-na-poddone-sht' => 'Количество на поддоне, шт.',
    'kolichestvo-sht-na-pog-m' => 'Количество шт. на пог.м',
    'kolichestvo-v-upakovke-m-p' => 'Количество в упаковке, м.п.',
    'kolvom2avto' => 'Количество м2/авто',
    'kolvom2rul' => 'Количество м2/рул',
    'kolvom2upak' => 'Количество м2/уп',
    'kolvom3avto' => 'Количество м3/авто',
    'kolvonapoddm2' => 'Количество на поддоне, м2',
    'kolvonapoddonepogm' => 'Количество на поддоне, пог.м',
    'kolvonapodm3' => 'Количество на поддоне, м3',
    'kolvoshavto' => 'Количество шт/авто',
    'kolvoshm2' => 'Количество шт/м2',
    'kolvoshm3' => 'Количество шт/м3',
    'kompressia' => 'Компрессия',
    'k_m2seam' => 'Кол-во шт в 1 м2 с учетом растворного шва',
    'k_m3seam' => 'Кол-во шт в 1 м3 с учетом растворного шва',
    'k_m3seamless' => 'Кол-во шт в 1 м3 без учета растворного шва',
    'massa' => 'Вес, кг',
    'massazam2' => 'Вес, кг/м2',
    'material' => 'Материал',
    'material-osnovaniya' => 'Материал основания',
    'modul-kislotnosti' => 'Модуль кислотности, не менее',
    'moos' => 'Твердость по шкале Моoса',
    'morzs' => 'Морозостойкость',
    'napolnitel' => 'Наполнитель',
    'nasypplotnost' => 'Насыпная плотность, кг/м3',
    'norma-rasshivki-mm' => 'Норма расшивки, мм',
    'oblastprimeneniya' => 'Область применения',
    'obyem_m3' => 'Объем, м3',
    'ognest' => 'Огнестойкость, °C',
    'okraskastoron' => 'Окраска сторон',
    'osnova' => 'Основа',
    'otkl-dlin' => 'Допускаемое отклонение по длине',
    'otkl-shir' => 'Допускаемое отклонение по ширине',
    'otkl-tolsh' => 'Допускаемое отклонение по толщине',
    'ottenok' => 'Оттенок',
    'pallet_num' => 'Кол-во на поддоне',
    'paropronicaem' => 'Паропроницаемость, мг/м*ч*Па',
    'paropronicaemost' => 'Коэффициент паропроницаемости',
    'plant' => 'Завод',
    'ploshad_m2' => 'Площадь, м2',
    'plotnost' => 'Плотность, кг/м3',
    'plotnost-g-m3' => 'Плотность, г/м3',
    'plotnost-v-kladke' => 'Плотность в кладке',
    'podvizhnost-rastvornoj-smesi' => 'Подвижность растворной смеси',
    'pokrytie' => 'Покрытие',
    'preimushchestva' => 'Преимущества  ',
    'primenenie' => 'Применение',
    'prochnaizgib' => 'Прочность на изгиб, МПа',
    'prochnaszhkgscm2' => 'Прочность на сжатие, кгс/см2',
    'prochnost' => 'Прочность при растяжении параллельно лицевым поверхностям, σt',
    'prochnost-scepleniya-s-osnovaniem-mpa' => 'Прочность сцепления с основанием, МПа',
    'prochnostnaszhatiempa' => 'Прочность на сжатие, МПа',
    'proizvoditel' => 'Производитель',
    'prokras' => 'Прокрас',
    'pustproc' => 'Пустотность %',
    'radiusr' => 'Радиус. R',
    'rashodkladrastkgm2' => 'Расход кладочного раствора, кг/м2',
    'raskhod-kg-m2' => 'Расход кг/м2',
    'raskhod-vody-l-kg' => 'Расход воды, л/кг',
    'raskhod-vody-na-upakovku-smesi-l' => 'Расход воды на упаковку смеси, л',
    'razmer' => 'Размер, ТхШхД',
    'razmer-frakcii-mm' => 'Размер фракции, мм',
    'razmer-mm' => 'Размер, мм',
    'razmer-uglovyh-ehlementov' => 'Размер угловых элементов',
    'sejsmostojkost' => 'Сейсмостойкость',
    'sezon-primeneniya' => 'Сезон применения',
    'shirina-shva-mm' => 'Ширина шва, мм',
    'shov' => 'Шов, мм',
    'solution_consumption' => 'Расход кладочного раствора, кг/шт',
    'sposobnaneseniya' => 'Способ нанесения',
    'srednij-raskhod-kleya' => 'Средний расход клея, кг/м2/пог.м',
    'srok-sluzhby' => 'Срок службы',
    'strana' => 'Страна',
    'strength_grade' => 'Марка прочности',
    'surface' => 'Поверхность',
    'svyazuyushchee' => 'Связующее',
    'szhimaemost' => 'Сжимаемость, %',
    'tekhnologiya-proizvodstva' => 'Технология производства',
    'temperatura-ehkspluatacii' => 'Температура эксплуатации',
    'temp_app' => 'Температура применения, С',
    'teploprovodnost' => 'Теплопроводность',
    'tip' => 'Тип',
    'tip-shtukaturki' => 'Тип штукатурки',
    'tipsystem' => 'Тип системы',
    'tolshchina-sloya-mm' => 'Толщина слоя, мм',
    'ton' => 'Тон',
    'ud-ehf-aktivnost-prir-radionuklidov' => 'Уд. эф. активность прир. радионуклидов',
    'unit' => 'Единица измерения',
    'upakovka' => 'Упаковка',
    'vid-cveta' => 'Вид цвета',
    'vid-ehlementa' => 'Вид элемента',
    'vid-kladki' => 'Вид кладки',
    'vid-rabot' => 'Вид работ',
    'viddekora' => 'Вид декора',
    'vlazhnost-suhoj-smesi' => 'Влажность сухой смеси, %',
    'vodopogloshchenie-kirpicha' => 'Водопоглощение кирпича, %',
    'vodopogloshenie' => 'Водопоглощение при полном погружении, не более',
    'vodopogloshenie3' => 'Водопоглощение при кратковременном и частичном погружении по массе, Wp',
    'vodopronicaemost' => 'Водопроницаемость',
    'voidness' => 'Пустотность',
    'vozduhopronicaemost' => 'Воздухопроницаемость по ГОСТ EN 29053-2011, l x 10-6, м3 /(Па∙м∙с)',
    'vremya-korrektirovki-min' => 'Время корректировки, мин',
    'vremya-raboty-ch' => 'Время работы, ч',
    'vremya-zhizni-ch' => 'Время жизни, ч',
    'vyhod-rastvora-up-l' => 'Выход раствора, уп/л',
    'vysota-mm' => 'Высота, мм',
    'v_upakovke' => 'Кол-во в упаковке, шт',
    'water_absorp' => 'Водопоглощение, %',
    'zvukoizolyaciya' => 'Звукоизоляция, дБ',
    'zvukopogloshenie' => 'Индекс звукопоглощения',
];

$liquidOptions = [
    'adgeziya',
    'class-pojar',
    'classprotivosk',
    'collection',
    'cvet',
    'cvet-proizvoditelya',
    'ehkspluatacionnaya-nagruzka-cherez-ch',
    'factsoprotteploper',
    'factura',
    'forma',
    'frostres_grade',
    'garantiya',
    'gruppa-istiraem',
    'indeks-izolyacii-vozdushnogo-shuma',
    'item_length',
    'item_thickness',
    'item_width',
    'iznosostojkost',
    'kislotostojkost',
    'klassbetona',
    'klassplotnosti',
    'kolichestvo-sht-na-pog-m',
    'kolichestvo-v-upakovke-m-p',
    'kolvom2avto',
    'kolvom2rul',
    'kolvom2upak',
    'kolvom3avto',
    'kolvonapoddm2',
    'kolvonapoddonepogm',
    'kolvonapodm3',
    'kolvoshavto',
    'kolvoshm2',
    'kolvoshm3',
    'k_m2seam',
    'k_m3seam',
    'k_m3seamless',
    'massa',
    'massazam2',
    'material',
    'material-osnovaniya',
    'moos',
    'morzs',
    'napolnitel',
    'nasypplotnost',
    'norma-rasshivki-mm',
    'oblastprimeneniya',
    'ognest',
    'okraskastoron',
    'osnova',
    'ottenok',
    'pallet_num',
    'paropronicaem',
    'plant',
    'ploshad_m2',
    'plotnost',
    'plotnost-g-m3',
    'plotnost-v-kladke',
    'podvizhnost-rastvornoj-smesi',
    'pokrytie',
    'preimushchestva',
    'primenenie',
    'prochnaizgib',
    'prochnaszhkgscm2',
    'prochnost-scepleniya-s-osnovaniem-mpa',
    'prochnostnaszhatiempa',
    'proizvoditel',
    'prokras',
    'pustproc',
    'radiusr',
    'rashodkladrastkgm2',
    'raskhod-kg-m2',
    'raskhod-vody-l-kg',
    'raskhod-vody-na-upakovku-smesi-l',
    'razmer-frakcii-mm',
    'razmer-mm',
    'razmer-uglovyh-ehlementov',
    'sejsmostojkost',
    'sezon-primeneniya',
    'shirina-shva-mm',
    'shov',
    'solution_consumption',
    'sposobnaneseniya',
    'srednij-raskhod-kleya',
    'srok-sluzhby',
    'strana',
    'strength_grade',
    'surface',
    'svyazuyushchee',
    'tekhnologiya-proizvodstva',
    'temperatura-ehkspluatacii',
    'temp_app',
    'teploprovodnost',
    'tip',
    'tip-shtukaturki',
    'tipsystem',
    'tolshchina-sloya-mm',
    'ton',
    'ud-ehf-aktivnost-prir-radionuklidov',
    'unit',
    'vid-cveta',
    'vid-ehlementa',
    'vid-kladki',
    'vid-rabot',
    'viddekora',
    'vlazhnost-suhoj-smesi',
    'vodopogloshchenie-kirpicha',
    'vodopronicaemost',
    'voidness',
    'vremya-korrektirovki-min',
    'vremya-raboty-ch',
    'vremya-zhizni-ch',
    'vyhod-rastvora-up-l',
    'vysota-mm',
    'v_upakovke',
    'water_absorp',
    'zvukoizolyaciya',
];

// Обходим массив со всеми НУЖНЫМИ (теми, которые есть в Excel) опциями
foreach ($liquidOptions as $key) {
    // Инициализируем Minishop2, он нам нужен для вызова процессоров
    $minishop2 = $modx->getService('miniShop2'); // Сам MiniShop2

    // Получаем название опции
    $caption = $options[$key];

    // Поиск опции по ключу
    $opt = $modx->getObject('msOption', ['key' => $key]);

    // Поиск опции по названию
    if (empty($opt)) {
        $opt = $modx->getObject('msOption', ['caption' => $caption]);
    }

    // Опция не нашлась, ее нужно создать
    if (empty($opt)) {
        $optValues = [
            'key' => $key,
            'type' => 'textfield',
            'caption' => $caption,
            'category' => 0
        ];

        // Вызов процессора для создания опции
        $res = $minishop2->runProcessor('mgr/settings/option/create', $optValues);

        // Не удалось создать опцию
        if (empty($res->response['object']['id'])) {
            echo 'Ошибка при попытке создать опцию с ключом ' . $key . '. Пропускается работа с ней.<br>';
            continue;
        } else {
            echo 'Опция с ключом ' . $key . '. успешно создана.<br>';
        }
    } else {
        echo 'Опция с ключом ' . $key . '. успешно найдена.<br>';
    }
}
