name: Deploy Stroymarket

on:
  workflow_dispatch:  # ручной запуск

jobs:
  deploy:
    runs-on: self-hosted  # выполняется на твоём сервере (self-hosted runner)

    steps:
      - name: Обновляем код в рабочей папке проекта
        run: |
          cd /test/fileupload
          git fetch --all
          git reset --hard origin/master